id: PA1BCECC5
initial_creation_type: ocr
source_metadata:
  volumes:
    a9f98b46e2434e54945a541944a2656a:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: གནས་ཆེན་པོ་བརྒྱད་ཀྱི་མཆོད་རྟེན་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
